spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cgiprojdevlibrary.cxyeb3wmov3g.us-east-1.rds.amazonaws.com:9871/cgiprojdevlibrary
    username: cgidevlib
    password: Password1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true